// Possible values for sorting tasks
export enum TaskSortKey {
  CREATED_AT__ASC = 'CREATED_AT__ASC',
  CREATED_AT__DESC = 'CREATED_AT__DESC',
  UPDATED_AT__ASC = 'UPDATED_AT__ASC',
  UPDATED_AT__DESC = 'UPDATED_AT__DESC',
  TITLE__ASC = 'TITLE__ASC',
  TITLE__DESC = 'TITLE__DESC',
  DUE_DATE__ASC = 'DUE_DATE__ASC',
  DUE_DATE__DESC = 'DUE_DATE__DESC',
}
